language: go

go:
  - "1.10"

env:
  global:
    - TEST_DB_USERNAME=user
    - TEST_DB_PASSWORD=password
    - TEST_DB_NAME=willandjagscooldb
    - TEST_DB_PORT=3306

services:
  - mysql 

before_install:
  - mysql -u root --password="" < test/schema.sql

install:
  - go get -v github.com/onsi/ginkgo/ginkgo
  - go get -v github.com/onsi/gomega
  - go get -v github.com/gin-contrib/static
  - go get -v github.com/gin-gonic/gin
  - go get -v github.com/go-sql-driver/mysql
  #  - go get -v -t ./...
  - export PATH=$PATH:$HOME/gopath/bin


script: 
  - cd backend && go test
  
  # ginkgo -r --randomizeAllSpecs --randomizeSuites --failOnPending --cover --trace --race --compilers=2
